export const GET_USER  ='GET_USER'
export const GET_USER_RED  ='GET_USER_RED'
export const ADD_USER  ='ADD_USER'
export const ADD_USER_RED  ='ADD_USER_RED'
export const UPDATE_USER  ='UPDATE_USER'
export const UPDATE_USER_RED  ='UPDATE_USER_RED'
export const DELETE_USER  ='DELETE_USER'
export const DELETE_USER_RED  ='DELETE_USER_RED'